name: Copy
on: [push]
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.API_TOKEN_GITHUB }}
        src_path: /Public/Guides/
        dst_path: /guides/
        dst_owner: qudo-code
        dst_repo_name: RUNBOOK
        dst_branch: master
        src_branch: master
        username: qudo-code
        email: qudo@matr.world

# name: Push File
# on: [push]
# jobs:
#     copy-file:
#       runs-on: ubuntu-latest
#       steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Pushes test file
#         uses: dmnemec/copy_file_to_another_repo_action@main
#         env:
#           API_TOKEN_GITHUB: ${{ secrets.pat }}
#         with:
#           source_file: './Public/Guides/'
#           destination_repo: 'qudo-code/RUNBOOK'
#           destination_folder: 'guides'
#           user_email: 'qudo@matr.world'
#           user_name: 'qudo-code'
#           commit_message: 'sync obsidian vault'